// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeDwWbcxB3_kkQcjeLfkg4o3wxkEdYhc8',
    appId: '1:420402658280:web:cd0f6d59243fcd2d05c25d',
    messagingSenderId: '420402658280',
    projectId: 'stage-ecommerce-178fc',
    authDomain: 'stage-ecommerce-178fc.firebaseapp.com',
    storageBucket: 'stage-ecommerce-178fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4oaqdjMfGXKVAA9Ewb50vo6LYZpFgOro',
    appId: '1:420402658280:android:eaf244671b863db305c25d',
    messagingSenderId: '420402658280',
    projectId: 'stage-ecommerce-178fc',
    storageBucket: 'stage-ecommerce-178fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvVxM9zlgG-5O0rpatwipgSzccvZqNYNU',
    appId: '1:420402658280:ios:875b8b6f8e0b06b605c25d',
    messagingSenderId: '420402658280',
    projectId: 'stage-ecommerce-178fc',
    storageBucket: 'stage-ecommerce-178fc.appspot.com',
    androidClientId: '420402658280-4qb305ls3kfdppsu64mq8pbd3huj267l.apps.googleusercontent.com',
    iosClientId: '420402658280-mkgoh09sc36c2dg8ca1cvvhkf5ntpu6n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvVxM9zlgG-5O0rpatwipgSzccvZqNYNU',
    appId: '1:420402658280:ios:084372509532337705c25d',
    messagingSenderId: '420402658280',
    projectId: 'stage-ecommerce-178fc',
    storageBucket: 'stage-ecommerce-178fc.appspot.com',
    androidClientId: '420402658280-4qb305ls3kfdppsu64mq8pbd3huj267l.apps.googleusercontent.com',
    iosClientId: '420402658280-8q9er2k1j2iqcmpttcqhe08aqrufb9pi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appStage.RunnerTests',
  );
}
